spring:
  profiles:
    active:
    - dev
  jackson:
    date-format: yyyy-MM-dd  
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb
server:
  servlet:
    context-path: /article
          