spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://112.74.179.143:3306/article_db?useUnicode=true&useSSL=false&characterEncoding=utf8
    url: jdbc:mysql://39.105.158.38:3306/article_db?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Abc123=!
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,logback
    poolPreparedStatements: true

### 系统参数配置 ###
article:
  appid: 
  secret: 
  AccessKeyId: 
  AccessKeySecret: 
  endpoint: 
  bucketName: 
