spring:
  profiles:
    active:
    - dev
  jackson:
    date-format: yyyy-MM-dd  
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb
server:
  servlet:
    context-path: /article
  port: 443
  ssl:
    key-store: classpath:cert-1541510749761_www.feigly.top.pfx
    key-store-password: fco0BFyj
    key-store-type: PKCS12
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: UUID    
          